print(False and True)
print(True and False)
print(True and True)
print(False and False)
print(True and True and False)
print(False and False and True)
print(False and True and True and True)
print(False and False and False and True)
print(False and False and False and False and True)
print(True and True and True and True and False)

print(False or True)
print(True or False)
print(True or True)
print(False or False)
print(True or True or False)
print(False or False or True)
print(False or True or True or True)
print(False or False or False or True)
print(False or False or False or False or True)
print(True or True or True or True or False)


print(True and True or False)
print(False or False and True)
print(False and True or True and True)
print(False or False and False and True)
print(False or False and False or False and True)
print(True and True or True and True and False)
print(True and True or True and True and False and False)
print(True and True or True and True and False or True)
print(True and True or True and True and False or True)
print(True and True or True and True and False and True)
print(True and True or True and True and False or False)


a = int(input("enter a "))
b = int(input("enter b "))
c = int(input("enter c "))
print(a>b)
print(a<b)
print(b>a)
print(b<a)
print(b<=a)
print(a<=b)
print(a>=b)
print(b>=a)
print(c>a<b)
print(a>b>c)