print(True or False)
print(False or True)
print(True or True)
print(False or False)
print(True or False or True)

print(True and False)
print(False and True)
print(True and True)
print(False and False)
print(False and True and False)

a = int(input("enter a"))
b = int(input("enter b"))
c = int(input("enter c"))
print(a and b or c)
print(b and c or a)
print(a and b and c or a)
print(c and c or a)
print(b and b or c and c)