print("I'm watching the show that the teacher gave us as a homework while writing this")
print("im probably going to write about what happened this week")
print("I played basketball with my dad")
print("My friend and I are planning a weekend gaming marathon!")
print("Im into history but it's kinda boring sometimes")
print("I tried that new pizza place; their pepperoni is the best!")
print("Im trying to beat my high score on that mobile game")
print("I think I finally figured out how to solve that math problem.")
print("Have you seen the latest Marvel movie? It was epic!")
print("I love playing chess sometimes its boring tho")
print("I just got a new skateboard; cant wait to show it off!")
print("We should totally have a movie night this weekend.")
print("I'm really getting tired writing all these codes")
print("I cant wait for the new season of my favorite show.")
print("I just started learning how to code its pretty cool!")
print("I joined basketball practices")
print("I had the funniest conversation with my friends at lunch!")
print("Im trying to learn how to play piano")
print("I found this awesome new channel on YouTube!")
print("I cant decide what to get for my birthday any ideas?")
print("My science project is going to be about space!")
print("I just discovered a new comic series")
print("I'd probably win in a chess tournament")
print("I had a crazy dream last night it felt so real I regretted waking up fr fr")
print("Im boooored")
print("I wish summer vacation would last forever but it didnt sadly")
print("Im trying to beat my friend's record in that racing game.")
print("My favorite snack right now is definitely doritos!")
print("I think Im going to try out for the school play.")
print("I finally finished that book everyone was raving about")
print("Have you tried that new ice cream flavor? Its amazing!")
print("I cant believe how much homework we have this week")
print("Im planning to start a YouTube channel; itll be fun!")
print("school is so boring sometimes")
print("I want to learn how to cook something cool this weekend.")
print("Im really excited about the school party coming up")
print("I just started playing a new video game")
print("Have you ever thought about what superpower youd want? I'd definitely get invisibility, for chad reasons ofc")
print("I cant wait to play with my friends after school!")
print("Im trying to convince my parents to let me get a dog!")